# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SinkLeader (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SinkLeader (iOS)
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Toast-Swift'               #, '~> 4.0.0'
  pod 'SwiftKeychainWrapper'
  
  pod 'Firebase/Analytics'    , '~> 7.1.0'
  pod 'Firebase/Messaging'  , '~> 7.1.0'
  
  pod 'SVGKit'
#  pod 'SDWebImageSVGKitPlugin'
end
